spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: root123
    schema: classpath:test.sql
mybatis:
  base-packages: com.deschen.restful.restfuldemo.pojo
logging:
  level:
    com.deschen.restful.restfuldemo.mapper: debug